language: julia
os:
    - osx
    - linux
julia:
    - 1.1
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false

## uncomment the following lines to override the default test script
script:
    - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'

 after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("TensorBoardLogger")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'using Pkg; cd(Pkg.dir("TensorBoardLogger")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
