language: julia
os:
    - osx
    - linux
julia:
    - 1.1
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.test("TensorBoardLogger"; coverage=true)';
after_success:
    - julia -e 'import Pkg; cd(Pkg.dir("TensorBoardLogger")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'import Pkg; cd(Pkg.dir("TensorBoardLogger")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
